import {
  boolean,
  date,
  index,
  integer,
  jsonb,
  pgTable,
  serial,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

/**
 * A campaign is one battle (e.g. "Rawia University Battle", September 2026).
 * All operational settings live here so admins can change them without code.
 */
export const campaigns = pgTable("campaigns", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  startDate: date("start_date").notNull(),
  endDate: date("end_date").notNull(),
  universityACode: text("university_a_code").notNull(),
  universityAName: text("university_a_name").notNull(),
  universityBCode: text("university_b_code").notNull(),
  universityBName: text("university_b_name").notNull(),
  /** Kiosk copy: "Who runs" / "the campus?" — editable so non-university campaigns read right. */
  headline: text("headline").notNull().default("Who runs"),
  headlineAccent: text("headline_accent").notNull().default("the campus?"),
  subline: text("subline").notNull().default("One tap for your university. The September tally is live."),
  active: boolean("active").notNull().default(true),
  /** Admin "manually reopen" override — accept votes even after end date. */
  reopened: boolean("reopened").notNull().default(false),
  showScoresOnVote: boolean("show_scores_on_vote").notNull().default(true),
  showConfirmationScore: boolean("show_confirmation_score").notNull().default(true),
  confirmationDurationMs: integer("confirmation_duration_ms").notNull().default(2500),
  attractEnabled: boolean("attract_enabled").notNull().default(true),
  attractTimeoutMs: integer("attract_timeout_ms").notNull().default(45000),
  /** "demo" while seeded test data is present, "live" after START LIVE CAMPAIGN. */
  mode: text("mode").notNull().default("demo"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const devices = pgTable("devices", {
  id: serial("id").primaryKey(),
  deviceName: text("device_name").notNull(),
  deviceIdentifier: text("device_identifier").notNull().unique(),
  /** SHA-256 of the device token. The raw token is shown once and never stored. */
  tokenHash: text("token_hash").notNull().unique(),
  active: boolean("active").notNull().default(true),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const votes = pgTable(
  "votes",
  {
    id: serial("id").primaryKey(),
    campaignId: integer("campaign_id")
      .notNull()
      .references(() => campaigns.id),
    university: text("university").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    deviceId: integer("device_id")
      .notNull()
      .references(() => devices.id),
    /** Random id generated by the kiosk for each screen "session" (one student). */
    sessionId: text("session_id").notNull(),
    /** Idempotency key: the kiosk retries with the same key, so a retry never double-counts. */
    clientVoteId: text("client_vote_id").notNull(),
    status: text("status").notNull().default("valid"),
    invalidatedAt: timestamp("invalidated_at", { withTimezone: true }),
    invalidatedBy: integer("invalidated_by").references(() => adminUsers.id),
    invalidReason: text("invalid_reason"),
  },
  (t) => [
    uniqueIndex("votes_client_vote_id_idx").on(t.clientVoteId),
    index("votes_campaign_status_created_idx").on(t.campaignId, t.status, t.createdAt),
    index("votes_device_created_idx").on(t.deviceId, t.createdAt),
  ],
);

export const adminUsers = pgTable("admin_users", {
  id: serial("id").primaryKey(),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const auditLogs = pgTable(
  "audit_logs",
  {
    id: serial("id").primaryKey(),
    adminUserId: integer("admin_user_id").references(() => adminUsers.id),
    adminEmail: text("admin_email").notNull(),
    action: text("action").notNull(),
    voteId: integer("vote_id"),
    reason: text("reason"),
    details: jsonb("details"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("audit_logs_created_idx").on(t.createdAt)],
);

export type Campaign = typeof campaigns.$inferSelect;
export type Device = typeof devices.$inferSelect;
export type Vote = typeof votes.$inferSelect;
export type AdminUser = typeof adminUsers.$inferSelect;
export type AuditLog = typeof auditLogs.$inferSelect;
